import {
  IconBook,
  IconNotes,
  IconUsers,
  IconFlame,
  IconStarFilled,
  IconMoon,
  IconPencil,
  IconTrophy,
  IconBookmark,
  IconMessageCircle2,
  IconUsersGroup,
  IconThumbUp,
  IconEyeOff,
  IconCompass,
  IconBooks,
  IconMoonStars,
  IconSunrise,
  IconBolt,
  IconBook2,
  IconEdit,
  IconShare,
  IconSearch,
  IconHeart,
  IconSparkles,
  IconRocket,
  IconClock,
  IconRefresh,
  IconTarget,
  IconCalendar,
  IconMedal,
} from '@tabler/icons-react'

export const achievementIcons = {
  book: IconBook,
  note: IconNotes,
  users: IconUsers,
  flame: IconFlame,
  star: IconStarFilled,
  moon: IconMoon,
  pencil: IconPencil,
  trophy: IconTrophy,
  bookmark: IconBookmark,
  message: IconMessageCircle2,
  usersgroup: IconUsersGroup,
  thumbup: IconThumbUp,
  eyeoff: IconEyeOff,
  compass: IconCompass,
  books: IconBooks,
  moonstars: IconMoonStars,
  sunrise: IconSunrise,
  bolt: IconBolt,
  book2: IconBook2,
  edit: IconEdit,
  share: IconShare,
  search: IconSearch,
  heart: IconHeart,
  sparkles: IconSparkles,
  rocket: IconRocket,
  clock: IconClock,
  refresh: IconRefresh,
  target: IconTarget,
  calendar: IconCalendar,
}

export const defaultAchievementIcon = IconMedal
